import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";


const Vazir = localFont({
  src: [
    {
      path: "../src/assets/fonts/Vazir.woff",
      weight: "400 500 600 700",
      style: "normal",
    },
  ],
  variable: "--font-vazir",
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${Vazir.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
